import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Ai(),
        ]),
      ),
    );
  }
}

class Ai extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1280,
          height: 2256,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: -100,
                child: Container(
                  width: 1570,
                  height: 540,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/1570x540"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 440,
                child: Container(
                  width: 1280,
                  height: 1242,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 346,
                top: 650,
                child: Text(
                  '1. 정보 입력',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xBFFF8200),
                    fontSize: 18,
                    fontFamily: 'Noto Sans KR',
                    fontWeight: FontWeight.w500,
                    height: 1.56,
                    letterSpacing: -0.36,
                  ),
                ),
              ),
              Positioned(
                left: 828,
                top: 650,
                child: Text(
                  '2. 결과 확인하기',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFFFF8200),
                    fontSize: 18,
                    fontFamily: 'Noto Sans KR',
                    fontWeight: FontWeight.w700,
                    height: 1.56,
                    letterSpacing: -0.36,
                  ),
                ),
              ),
              Positioned(
                left: 144,
                top: 705,
                child: Container(
                  width: 994,
                  height: 12,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 7,
                        child: Container(
                          width: 994,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 994,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1.60,
                                        strokeAlign: BorderSide.strokeAlignCenter,
                                        color: const Color(0xFFFFBF7D),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 497,
                        top: 0,
                        child: Container(
                          width: 497,
                          height: 12,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 497,
                                  height: 12,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFFF8200),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 144,
                top: 566,
                child: Container(
                  width: 994,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 994,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1.60,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFD2D2D2),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 496,
                top: 566,
                child: Container(
                  width: 289,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 289,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1.60,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFFF8200),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 142,
                top: 500,
                child: Container(
                  width: 996,
                  height: 40,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 996,
                          height: 40,
                          child: Text(
                            'AI 시세 조회하기',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: const Color(0xFF1A1A1A),
                              fontSize: 36,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w700,
                              height: 0.89,
                              letterSpacing: -0.72,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 142,
                top: 767,
                child: Container(
                  width: 996,
                  height: 1142,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF4D4D53),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 192,
                top: 1351,
                child: Container(
                  width: 896,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 896,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1.60,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFD2D2D2),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 424,
                top: 1385,
                child: Container(
                  width: 671,
                  height: 349,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 671,
                          height: 349,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/671x349"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 193,
                top: 913,
                child: Container(
                  width: 85,
                  height: 32,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Text(
                          '시세 요약',
                          style: TextStyle(
                            color: const Color(0xFF1A1A1A),
                            fontSize: 22,
                            fontFamily: 'Noto Sans KR',
                            fontWeight: FontWeight.w700,
                            height: 1.45,
                            letterSpacing: -0.44,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 193,
                top: 1401,
                child: Container(
                  width: 104,
                  height: 32,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 104,
                          height: 32,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  '시세 그래프',
                                  style: TextStyle(
                                    color: const Color(0xFF1A1A1A),
                                    fontSize: 22,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.45,
                                    letterSpacing: -0.44,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 186,
                top: 990,
                child: Container(
                  width: 896,
                  height: 316,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 896,
                          height: 316,
                          decoration: BoxDecoration(color: const Color(0xFFF6F6F6)),
                        ),
                      ),
                      Positioned(
                        left: 362,
                        top: 146,
                        child: Container(
                          width: 229,
                          height: 84,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 82,
                                  height: 32,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Text(
                                          '평균 거래가',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: const Color(0xFF1A1A1A),
                                            fontSize: 18,
                                            fontFamily: 'Pretendard',
                                            fontWeight: FontWeight.w700,
                                            height: 1.78,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 32,
                                child: Container(
                                  width: 209,
                                  height: 52,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Text(
                                          '1,100,000원',
                                          style: TextStyle(
                                            color: const Color(0xFFBE6201),
                                            fontSize: 36,
                                            fontFamily: 'Pretendard',
                                            fontWeight: FontWeight.w900,
                                            height: 1.44,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 57,
                        top: 31,
                        child: Container(
                          width: 796,
                          height: 40,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 796,
                                  height: 40,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 796,
                                          height: 40,
                                          decoration: BoxDecoration(color: const Color(0xFFFF8200)),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 302,
                                top: 4,
                                child: Container(
                                  width: 192,
                                  height: 32,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Text(
                                          '25알원 R ONE 로드자전거',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 18,
                                            fontFamily: 'Pretendard',
                                            fontWeight: FontWeight.w700,
                                            height: 1.78,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 631,
                        top: 145,
                        child: Container(
                          width: 220,
                          height: 36,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 220,
                                  height: 36,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFFF8200),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 55,
                                top: 5,
                                child: Container(
                                  width: 140,
                                  height: 26,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Text(
                                          '상한가: 1,500,000원',
                                          textAlign: TextAlign.right,
                                          style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 16,
                                            fontFamily: 'Noto Sans KR',
                                            fontWeight: FontWeight.w700,
                                            height: 1.62,
                                            letterSpacing: -0.32,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 25,
                                top: 26,
                                child: Container(
                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                                  width: 16,
                                  height: 16,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 631,
                        top: 190,
                        child: Container(
                          width: 220,
                          height: 36,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 220,
                                  height: 36,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 220,
                                          height: 36,
                                          decoration: ShapeDecoration(
                                            color: Colors.white,
                                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 69,
                                top: 5,
                                child: Container(
                                  width: 126,
                                  height: 26,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Text(
                                          '하한가: 500,000원',
                                          textAlign: TextAlign.right,
                                          style: TextStyle(
                                            color: const Color(0xFF1A1A1A),
                                            fontSize: 16,
                                            fontFamily: 'Noto Sans KR',
                                            fontWeight: FontWeight.w700,
                                            height: 1.62,
                                            letterSpacing: -0.32,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 57,
                        top: 95,
                        child: Container(
                          width: 232,
                          height: 181,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 232,
                                  height: 181,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 232,
                                          height: 181,
                                          decoration: ShapeDecoration(
                                            color: Colors.white,
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(20),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 10,
                                top: 7,
                                child: Container(
                                  width: 213,
                                  height: 167,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 213,
                                          height: 167,
                                          decoration: BoxDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage("https://placehold.co/213x167"),
                                              fit: BoxFit.fill,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 192,
                top: 1799,
                child: Container(
                  width: 896,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 896,
                          height: 60,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 255,
                                top: 0,
                                child: Container(
                                  width: 641,
                                  height: 60,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 641,
                                          height: 60,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 641,
                                                  height: 60,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFFFF8200),
                                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 260,
                                        top: 16,
                                        child: Container(
                                          width: 122,
                                          height: 28,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Text(
                                                  '맞춤 자전거 찾기',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: Colors.white,
                                                    fontSize: 18,
                                                    fontFamily: 'Noto Sans KR',
                                                    fontWeight: FontWeight.w700,
                                                    height: 1.56,
                                                    letterSpacing: -0.36,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 235,
                                  height: 60,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 235,
                                          height: 60,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 235,
                                                  height: 60,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFF868686),
                                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 67,
                                        top: 16,
                                        child: Container(
                                          width: 102,
                                          height: 28,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Text(
                                                  '다시 조회하기',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: Colors.white,
                                                    fontSize: 18,
                                                    fontFamily: 'Noto Sans KR',
                                                    fontWeight: FontWeight.w500,
                                                    height: 1.56,
                                                    letterSpacing: -0.36,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 142,
                top: 767,
                child: Container(
                  width: 996,
                  height: 96,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 996,
                          height: 96,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 996,
                                  height: 96,
                                  decoration: BoxDecoration(color: const Color(0xFF4D4D53)),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 50,
                        top: 17,
                        child: Container(
                          width: 324,
                          height: 62,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 154,
                                  height: 32,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Text(
                                          'AI 시세 분석 결과',
                                          style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 22,
                                            fontFamily: 'Noto Sans KR',
                                            fontWeight: FontWeight.w700,
                                            height: 1.45,
                                            letterSpacing: -0.44,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 36,
                                child: Container(
                                  width: 324,
                                  height: 26,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Text(
                                          '실시간 데이터를 기반으로 분석된 예상 시세입니다.',
                                          style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 16,
                                            fontFamily: 'Noto Sans KR',
                                            fontWeight: FontWeight.w500,
                                            height: 1.62,
                                            letterSpacing: -0.32,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 1969,
                child: Container(
                  width: 1280,
                  height: 287,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: Colors.white),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 1280,
                          height: 287,
                          decoration: BoxDecoration(color: Colors.white),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 358,
                        child: Container(
                          width: 1280,
                          height: 216,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/1280x216"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 40,
                        top: 80,
                        child: Container(
                          width: 107,
                          height: 30,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/107x30"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 243,
                        top: 80,
                        child: SizedBox(
                          width: 489,
                          height: 18,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: '본사 :',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                                TextSpan(
                                  text: ' 경기도 양주시 칠봉산로120번길 82(봉양동) | 경기도 양주시 봉양동 33-4',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w400,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 243,
                        top: 136,
                        child: SizedBox(
                          width: 285,
                          height: 18,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: '사업자 번호 :',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                                TextSpan(
                                  text: ' 107-87-33730',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w400,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 40,
                        top: 194,
                        child: Container(
                          width: 1197,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFBEBDBD),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 243,
                        top: 108,
                        child: SizedBox(
                          width: 128,
                          height: 18,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: 'TEL :',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                                TextSpan(
                                  text: ' 031) 727 - 9100',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w400,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 401,
                        top: 108,
                        child: SizedBox(
                          width: 126,
                          height: 18,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: 'A/S :',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                                TextSpan(
                                  text: ' 031) 859 - 0100',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w400,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 557,
                        top: 108,
                        child: SizedBox(
                          width: 125,
                          height: 18,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: 'FAX :',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                                TextSpan(
                                  text: '031) 727 - 9291',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w400,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1130,
                        top: 80,
                        child: SizedBox(
                          width: 110,
                          height: 18,
                          child: Text(
                            'HOME',
                            textAlign: TextAlign.right,
                            style: TextStyle(
                              color: const Color(0xFF1A1A1A),
                              fontSize: 14,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w500,
                              height: 2,
                              letterSpacing: -0.28,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1125,
                        top: 108,
                        child: SizedBox(
                          width: 115,
                          height: 18,
                          child: Text(
                            'AI 맞춤 자전거 찾기',
                            textAlign: TextAlign.right,
                            style: TextStyle(
                              color: const Color(0xFF1A1A1A),
                              fontSize: 14,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w500,
                              height: 2,
                              letterSpacing: -0.28,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1125,
                        top: 136,
                        child: SizedBox(
                          width: 115,
                          height: 18,
                          child: Text(
                            'AI 시세 조회하기',
                            textAlign: TextAlign.right,
                            style: TextStyle(
                              color: const Color(0xFF1A1A1A),
                              fontSize: 14,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w500,
                              height: 2,
                              letterSpacing: -0.28,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 778,
                        top: 219,
                        child: SizedBox(
                          width: 462,
                          height: 18,
                          child: Text(
                            'Copyright ©  2025 BikeMerics. All Rights Reserved.',
                            textAlign: TextAlign.right,
                            style: TextStyle(
                              color: const Color(0xFF868686),
                              fontSize: 14,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w400,
                              height: 2,
                              letterSpacing: -0.28,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 138,
                        top: 219,
                        child: SizedBox(
                          width: 51,
                          height: 18,
                          child: Text(
                            'Family',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 14,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w700,
                              height: 1.86,
                              letterSpacing: -0.28,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 40,
                        top: 214,
                        child: Container(
                          width: 85,
                          height: 23,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/85x23"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 1280,
                          height: 40,
                          decoration: BoxDecoration(color: const Color(0xFFFF8200)),
                        ),
                      ),
                      Positioned(
                        left: 1155,
                        top: 14,
                        child: SizedBox(
                          width: 85,
                          child: Text(
                            'FAMILY SITE',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w400,
                              height: 1,
                              letterSpacing: -0.24,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 268,
                        top: 14,
                        child: SizedBox(
                          width: 44,
                          child: Text(
                            '회사소개',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w400,
                              height: 1,
                              letterSpacing: -0.24,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 176,
                        top: 14,
                        child: SizedBox(
                          width: 44,
                          child: Text(
                            '법적고지',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w400,
                              height: 1,
                              letterSpacing: -0.24,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 40,
                        top: 14,
                        child: SizedBox(
                          width: 88,
                          child: Text(
                            '개인정보처리방침',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w400,
                              height: 1,
                              letterSpacing: -0.24,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 244,
                        top: 13,
                        child: Container(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          width: 14,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 152,
                        top: 13,
                        child: Container(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          width: 14,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 243,
                top: 26,
                child: SizedBox(
                  width: 42,
                  child: Text(
                    'HOME',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w700,
                      height: 1.71,
                      letterSpacing: -0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 477,
                top: 26,
                child: SizedBox(
                  width: 95,
                  child: Text(
                    'AI 시세 조회하기',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w700,
                      height: 1.71,
                      letterSpacing: -0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 325,
                top: 26,
                child: SizedBox(
                  width: 112,
                  child: Text(
                    'AI 맞춤 자전거 찾기',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF3E3A39),
                      fontSize: 14,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w700,
                      height: 1.71,
                      letterSpacing: -0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 967,
                top: 26,
                child: SizedBox(
                  width: 40,
                  child: Text(
                    '로그인',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w700,
                      height: 1.71,
                      letterSpacing: -0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1027,
                top: 26,
                child: SizedBox(
                  width: 52,
                  child: Text(
                    '회원가입',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w700,
                      height: 1.71,
                      letterSpacing: -0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1099,
                top: 26,
                child: SizedBox(
                  width: 39,
                  child: Text(
                    '알톤몰',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w700,
                      height: 1.71,
                      letterSpacing: -0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1017,
                top: 34,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                  width: 14,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1089,
                top: 34,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                  width: 14,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1210,
                top: 34,
                child: SizedBox(
                  width: 30,
                  child: Text(
                    'KOR',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w400,
                      height: 1,
                      letterSpacing: -0.24,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1184,
                top: 32,
                child: Container(
                  width: 20,
                  height: 16,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(2)),
                  ),
                ),
              ),
              Positioned(
                left: 142,
                top: 190,
                child: SizedBox(
                  width: 590,
                  height: 36,
                  child: Text(
                    '단 한 번의 조회로 정확한 시세 분석',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 36,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w700,
                      height: 0.89,
                      letterSpacing: -0.72,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 142,
                top: 251,
                child: SizedBox(
                  width: 691,
                  height: 86,
                  child: Text(
                    '방대한 데이터를 학습한 AI가 데이터를 종합 분석하여, \n자전거의 현재 시세부터 미래 가치까지 정밀하게 제공합니다. \n복잡한 데이터 해석 없이도, 누구나 손쉽게 신뢰할 수 있는 가격 정보를 확인할 수 있습니다. ',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 18,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w500,
                      height: 1.56,
                      letterSpacing: -0.36,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
        Container(
          width: 16,
          height: 16,
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 16,
                  height: 16,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 16,
                        top: 0,
                        child: Container(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          width: 29.01,
                          height: 16,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}