import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Ai(),
        ]),
      ),
    );
  }
}

class Ai extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 1280,
          height: 2218,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: -100,
                child: Container(
                  width: 1718,
                  height: 591,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/1718x591"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 440,
                child: Container(
                  width: 1280,
                  height: 1242,
                  decoration: BoxDecoration(color: Colors.white),
                ),
              ),
              Positioned(
                left: 346,
                top: 650,
                child: Container(
                  width: 89,
                  height: 28,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Text(
                          '1. 정보 입력',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFFFF8200),
                            fontSize: 18,
                            fontFamily: 'Noto Sans KR',
                            fontWeight: FontWeight.w700,
                            height: 1.56,
                            letterSpacing: -0.36,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 828,
                top: 650,
                child: Container(
                  width: 120,
                  height: 28,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Text(
                          '2. 결과 확인하기',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF868686),
                            fontSize: 18,
                            fontFamily: 'Noto Sans KR',
                            fontWeight: FontWeight.w500,
                            height: 1.56,
                            letterSpacing: -0.36,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 142,
                top: 705,
                child: Container(
                  width: 996,
                  height: 12,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 2,
                        top: 7,
                        child: Container(
                          width: 994,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 994,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1.60,
                                        strokeAlign: BorderSide.strokeAlignCenter,
                                        color: const Color(0xFFFFBF7D),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 497,
                          height: 12,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 497,
                                  height: 12,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFFF8200),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(6)),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 144,
                top: 566,
                child: Container(
                  width: 994,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 994,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 994,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1.60,
                                        strokeAlign: BorderSide.strokeAlignCenter,
                                        color: const Color(0xFFD2D2D2),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 352,
                        top: 0,
                        child: Container(
                          width: 289,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 289,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1.60,
                                        strokeAlign: BorderSide.strokeAlignCenter,
                                        color: const Color(0xFFFF8200),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 142,
                top: 500,
                child: Container(
                  width: 996,
                  height: 40,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 996,
                          height: 40,
                          child: Text(
                            'AI 시세 조회하기',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: const Color(0xFF1A1A1A),
                              fontSize: 36,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w700,
                              height: 0.89,
                              letterSpacing: -0.72,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 142,
                top: 767,
                child: Container(
                  width: 996,
                  height: 1104,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF4D4D53),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 192,
                top: 1761,
                child: Container(
                  width: 896,
                  height: 60,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 255,
                        top: 0,
                        child: Container(
                          width: 641,
                          height: 60,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 641,
                                  height: 60,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 641,
                                          height: 60,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFFF8200),
                                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 269,
                                        top: 16,
                                        child: Container(
                                          width: 102,
                                          height: 28,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Text(
                                                  '결과 확인하기',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: Colors.white,
                                                    fontSize: 18,
                                                    fontFamily: 'Noto Sans KR',
                                                    fontWeight: FontWeight.w700,
                                                    height: 1.56,
                                                    letterSpacing: -0.36,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 235,
                          height: 60,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 235,
                                  height: 60,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFF868686),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 93,
                        top: 16,
                        child: Container(
                          width: 49,
                          height: 28,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  '초기화',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: Colors.white,
                                    fontSize: 18,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w500,
                                    height: 1.56,
                                    letterSpacing: -0.36,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 142,
                top: 767,
                child: Container(
                  width: 996,
                  height: 96,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 996,
                          height: 96,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 996,
                                  height: 96,
                                  decoration: BoxDecoration(color: const Color(0xFF4D4D53)),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 50,
                        top: 17,
                        child: Container(
                          width: 429,
                          height: 62,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 149,
                                  height: 32,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Text(
                                          '자전거 정보 입력',
                                          style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 22,
                                            fontFamily: 'Noto Sans KR',
                                            fontWeight: FontWeight.w700,
                                            height: 1.45,
                                            letterSpacing: -0.44,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 36,
                                child: Container(
                                  width: 429,
                                  height: 26,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Text(
                                          '모델명, 연식, 상태를 입력하면 AI가 정확한 시세를 분석해 드립니다.',
                                          style: TextStyle(
                                            color: Colors.white,
                                            fontSize: 16,
                                            fontFamily: 'Noto Sans KR',
                                            fontWeight: FontWeight.w500,
                                            height: 1.62,
                                            letterSpacing: -0.32,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 192,
                top: 913,
                child: Container(
                  width: 896,
                  height: 132,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 66,
                          height: 28,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  '브랜드명',
                                  style: TextStyle(
                                    color: const Color(0xFF1A1A1A),
                                    fontSize: 18,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.56,
                                    letterSpacing: -0.36,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 44,
                        child: Container(
                          width: 896,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 896,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1.60,
                                        strokeAlign: BorderSide.strokeAlignCenter,
                                        color: const Color(0xFFD2D2D2),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 84,
                        child: Container(
                          width: 896,
                          height: 48,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 896,
                                  height: 48,
                                  decoration: BoxDecoration(color: const Color(0xFFF6F6F6)),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 14,
                        top: 94,
                        child: Container(
                          width: 129,
                          height: 28,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  '브랜드명을 입력하세요.',
                                  style: TextStyle(
                                    color: const Color(0xFF868686),
                                    fontSize: 14,
                                    fontFamily: 'Pretendard',
                                    fontWeight: FontWeight.w400,
                                    height: 2,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 846,
                        top: 96,
                        child: Container(
                          width: 24,
                          height: 24,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 192,
                top: 1121,
                child: Container(
                  width: 896,
                  height: 132,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 49,
                          height: 28,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  '모델명',
                                  style: TextStyle(
                                    color: const Color(0xFF1A1A1A),
                                    fontSize: 18,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.56,
                                    letterSpacing: -0.36,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 44,
                        child: Container(
                          width: 896,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 896,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1.60,
                                        strokeAlign: BorderSide.strokeAlignCenter,
                                        color: const Color(0xFFD2D2D2),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 84,
                        child: Container(
                          width: 896,
                          height: 48,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 896,
                                  height: 48,
                                  decoration: BoxDecoration(color: const Color(0xFFF6F6F6)),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 94,
                        child: Container(
                          width: 116,
                          height: 28,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  '모델명을 입력하세요.',
                                  style: TextStyle(
                                    color: const Color(0xFF868686),
                                    fontSize: 14,
                                    fontFamily: 'Pretendard',
                                    fontWeight: FontWeight.w400,
                                    height: 2,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 848,
                        top: 96,
                        child: Container(
                          width: 24,
                          height: 24,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 192,
                top: 1329,
                child: Container(
                  width: 896,
                  height: 132,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 84,
                        child: Container(
                          width: 896,
                          height: 48,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 896,
                                  height: 48,
                                  decoration: BoxDecoration(color: const Color(0xFFF6F6F6)),
                                ),
                              ),
                              Positioned(
                                left: 16,
                                top: 10,
                                child: Container(
                                  width: 34,
                                  height: 28,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Text(
                                          '2023',
                                          style: TextStyle(
                                            color: const Color(0xFF1A1A1A),
                                            fontSize: 14,
                                            fontFamily: 'Pretendard',
                                            fontWeight: FontWeight.w400,
                                            height: 2,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 33,
                          height: 28,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  '연식',
                                  style: TextStyle(
                                    color: const Color(0xFF1A1A1A),
                                    fontSize: 18,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.56,
                                    letterSpacing: -0.36,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 44,
                        child: Container(
                          width: 896,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 896,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1.60,
                                        strokeAlign: BorderSide.strokeAlignCenter,
                                        color: const Color(0xFFD2D2D2),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 1029,
                top: 1416,
                child: Container(
                  width: 48,
                  height: 42,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 48,
                          height: 20,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFF1A1A1A),
                              ),
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 22,
                        child: Container(
                          width: 48,
                          height: 20,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFF1A1A1A),
                              ),
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 19,
                        top: 29,
                        child: Container(width: 10, height: 6, child: Stack()),
                      ),
                      Positioned(
                        left: 19,
                        top: 7,
                        child: Container(width: 10, height: 6, child: Stack()),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 630,
                top: 1531,
                child: Text(
                  ' ',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 14,
                    fontFamily: 'Pretendard',
                    fontWeight: FontWeight.w400,
                    height: 2,
                  ),
                ),
              ),
              Positioned(
                left: 192,
                top: 1537,
                child: Container(
                  width: 896,
                  height: 144,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 86,
                          height: 28,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  '자전거 상태',
                                  style: TextStyle(
                                    color: const Color(0xFF1A1A1A),
                                    fontSize: 18,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.56,
                                    letterSpacing: -0.36,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 44,
                        child: Container(
                          width: 896,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 896,
                                  decoration: ShapeDecoration(
                                    shape: RoundedRectangleBorder(
                                      side: BorderSide(
                                        width: 1.60,
                                        strokeAlign: BorderSide.strokeAlignCenter,
                                        color: const Color(0xFFD2D2D2),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 84,
                        child: Container(
                          width: 286,
                          height: 60,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 286,
                                  height: 60,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 286,
                                          height: 60,
                                          decoration: ShapeDecoration(
                                            color: Colors.white,
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 1.60,
                                                color: const Color(0xFFD2D2D2),
                                              ),
                                              borderRadius: BorderRadius.circular(4),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 157,
                                top: 16,
                                child: Container(
                                  width: 17,
                                  height: 28,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Text(
                                          '상',
                                          style: TextStyle(
                                            color: const Color(0xFF4D4D53),
                                            fontSize: 18,
                                            fontFamily: 'Noto Sans KR',
                                            fontWeight: FontWeight.w700,
                                            height: 1.56,
                                            letterSpacing: -0.36,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 112,
                                top: 15,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 30,
                                          height: 30,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFFF8200),
                                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(7)),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 119,
                                top: 24,
                                child: Container(
                                  width: 16,
                                  height: 12,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 6,
                                        child: Container(
                                          width: 4,
                                          height: 6,
                                          decoration: ShapeDecoration(
                                            color: Colors.white,
                                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(1)),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 6,
                                        top: 3,
                                        child: Container(
                                          width: 4,
                                          height: 9,
                                          decoration: ShapeDecoration(
                                            color: Colors.white,
                                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(1)),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 12,
                                        top: 0,
                                        child: Container(
                                          width: 4,
                                          height: 12,
                                          decoration: ShapeDecoration(
                                            color: Colors.white,
                                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(1)),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 305,
                        top: 84,
                        child: Container(
                          width: 286,
                          height: 60,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 286,
                                  height: 60,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 286,
                                          height: 60,
                                          decoration: ShapeDecoration(
                                            color: const Color(0xFFFF8200),
                                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 112,
                                top: 15,
                                child: Container(
                                  width: 62,
                                  height: 30,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 45,
                                        top: 1,
                                        child: Container(
                                          width: 17,
                                          height: 28,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Text(
                                                  '중',
                                                  style: TextStyle(
                                                    color: Colors.white,
                                                    fontSize: 18,
                                                    fontFamily: 'Noto Sans KR',
                                                    fontWeight: FontWeight.w700,
                                                    height: 1.56,
                                                    letterSpacing: -0.36,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(width: 30, height: 30, child: Stack()),
                                      ),
                                      Positioned(
                                        left: 7,
                                        top: 9,
                                        child: Container(
                                          width: 16,
                                          height: 12,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 6,
                                                child: Container(
                                                  width: 4,
                                                  height: 6,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFFFF8200),
                                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(1)),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 6,
                                                top: 3,
                                                child: Container(
                                                  width: 4,
                                                  height: 9,
                                                  decoration: ShapeDecoration(
                                                    color: const Color(0xFFFF8200),
                                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(1)),
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 12,
                                                top: 0,
                                                child: Container(
                                                  width: 4,
                                                  height: 12,
                                                  decoration: ShapeDecoration(
                                                    shape: RoundedRectangleBorder(
                                                      side: BorderSide(
                                                        width: 1,
                                                        color: const Color(0xFFFF8200),
                                                      ),
                                                      borderRadius: BorderRadius.circular(1),
                                                    ),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 610,
                        top: 84,
                        child: Container(
                          width: 286,
                          height: 60,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 286,
                                  height: 60,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 286,
                                          height: 60,
                                          decoration: ShapeDecoration(
                                            color: Colors.white,
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(
                                                width: 1.60,
                                                color: const Color(0xFFD2D2D2),
                                              ),
                                              borderRadius: BorderRadius.circular(4),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 157,
                                top: 16,
                                child: Container(
                                  width: 17,
                                  height: 28,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Text(
                                          '하',
                                          style: TextStyle(
                                            color: const Color(0xFF4D4D53),
                                            fontSize: 18,
                                            fontFamily: 'Noto Sans KR',
                                            fontWeight: FontWeight.w700,
                                            height: 1.56,
                                            letterSpacing: -0.36,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 112,
                                top: 15,
                                child: Container(
                                  width: 30,
                                  height: 30,
                                  decoration: ShapeDecoration(
                                    color: const Color(0xFFFF8200),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(7)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 119,
                                top: 24,
                                child: Container(
                                  width: 16,
                                  height: 12,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 6,
                                        child: Container(
                                          width: 4,
                                          height: 6,
                                          decoration: ShapeDecoration(
                                            color: Colors.white,
                                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(1)),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 6,
                                        top: 3,
                                        child: Container(
                                          width: 4,
                                          height: 9,
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(width: 1, color: Colors.white),
                                              borderRadius: BorderRadius.circular(1),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 12,
                                        top: 0,
                                        child: Container(
                                          width: 4,
                                          height: 12,
                                          decoration: ShapeDecoration(
                                            shape: RoundedRectangleBorder(
                                              side: BorderSide(width: 1, color: Colors.white),
                                              borderRadius: BorderRadius.circular(1),
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 243,
                top: 26,
                child: SizedBox(
                  width: 42,
                  child: Text(
                    'HOME',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w700,
                      height: 1.71,
                      letterSpacing: -0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 477,
                top: 26,
                child: SizedBox(
                  width: 95,
                  child: Text(
                    'AI 시세 조회하기',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w700,
                      height: 1.71,
                      letterSpacing: -0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 325,
                top: 26,
                child: SizedBox(
                  width: 112,
                  child: Text(
                    'AI 맞춤 자전거 찾기',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF3E3A39),
                      fontSize: 14,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w700,
                      height: 1.71,
                      letterSpacing: -0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 967,
                top: 26,
                child: SizedBox(
                  width: 40,
                  child: Text(
                    '로그인',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w700,
                      height: 1.71,
                      letterSpacing: -0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1027,
                top: 26,
                child: SizedBox(
                  width: 52,
                  child: Text(
                    '회원가입',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w700,
                      height: 1.71,
                      letterSpacing: -0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1099,
                top: 26,
                child: SizedBox(
                  width: 39,
                  child: Text(
                    '알톤몰',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 14,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w700,
                      height: 1.71,
                      letterSpacing: -0.28,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1017,
                top: 34,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                  width: 14,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1089,
                top: 34,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                  width: 14,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1210,
                top: 34,
                child: SizedBox(
                  width: 30,
                  child: Text(
                    'KOR',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 12,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w400,
                      height: 1,
                      letterSpacing: -0.24,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1184,
                top: 32,
                child: Container(
                  width: 20,
                  height: 16,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(2)),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 1931,
                child: Container(
                  width: 1280,
                  height: 287,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(color: Colors.white),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 1280,
                          height: 287,
                          decoration: BoxDecoration(color: Colors.white),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 358,
                        child: Container(
                          width: 1280,
                          height: 216,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/1280x216"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 40,
                        top: 80,
                        child: Container(
                          width: 107,
                          height: 30,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/107x30"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 243,
                        top: 80,
                        child: SizedBox(
                          width: 489,
                          height: 18,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: '본사 :',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                                TextSpan(
                                  text: ' 경기도 양주시 칠봉산로120번길 82(봉양동) | 경기도 양주시 봉양동 33-4',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w400,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 243,
                        top: 136,
                        child: SizedBox(
                          width: 285,
                          height: 18,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: '사업자 번호 :',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                                TextSpan(
                                  text: ' 107-87-33730',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w400,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 40,
                        top: 194,
                        child: Container(
                          width: 1197,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFBEBDBD),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 243,
                        top: 108,
                        child: SizedBox(
                          width: 128,
                          height: 18,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: 'TEL :',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                                TextSpan(
                                  text: ' 031) 727 - 9100',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w400,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 401,
                        top: 108,
                        child: SizedBox(
                          width: 126,
                          height: 18,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: 'A/S :',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                                TextSpan(
                                  text: ' 031) 859 - 0100',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w400,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 557,
                        top: 108,
                        child: SizedBox(
                          width: 125,
                          height: 18,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: 'FAX :',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w700,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                                TextSpan(
                                  text: '031) 727 - 9291',
                                  style: TextStyle(
                                    color: Colors.black,
                                    fontSize: 14,
                                    fontFamily: 'Noto Sans KR',
                                    fontWeight: FontWeight.w400,
                                    height: 1.86,
                                    letterSpacing: -0.28,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1130,
                        top: 80,
                        child: SizedBox(
                          width: 110,
                          height: 18,
                          child: Text(
                            'HOME',
                            textAlign: TextAlign.right,
                            style: TextStyle(
                              color: const Color(0xFF1A1A1A),
                              fontSize: 14,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w500,
                              height: 2,
                              letterSpacing: -0.28,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1125,
                        top: 108,
                        child: SizedBox(
                          width: 115,
                          height: 18,
                          child: Text(
                            'AI 맞춤 자전거 찾기',
                            textAlign: TextAlign.right,
                            style: TextStyle(
                              color: const Color(0xFF1A1A1A),
                              fontSize: 14,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w500,
                              height: 2,
                              letterSpacing: -0.28,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1125,
                        top: 136,
                        child: SizedBox(
                          width: 115,
                          height: 18,
                          child: Text(
                            'AI 시세 조회하기',
                            textAlign: TextAlign.right,
                            style: TextStyle(
                              color: const Color(0xFF1A1A1A),
                              fontSize: 14,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w500,
                              height: 2,
                              letterSpacing: -0.28,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 778,
                        top: 219,
                        child: SizedBox(
                          width: 462,
                          height: 18,
                          child: Text(
                            'Copyright ©  2025 BikeMerics. All Rights Reserved.',
                            textAlign: TextAlign.right,
                            style: TextStyle(
                              color: const Color(0xFF868686),
                              fontSize: 14,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w400,
                              height: 1.86,
                              letterSpacing: -0.28,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 138,
                        top: 217,
                        child: SizedBox(
                          width: 62,
                          height: 18,
                          child: Text(
                            'Family',
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 18,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w700,
                              height: 1.56,
                              letterSpacing: -0.36,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 40,
                        top: 214,
                        child: Container(
                          width: 85,
                          height: 23,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/85x23"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 1280,
                          height: 40,
                          decoration: BoxDecoration(color: const Color(0xFFFF8200)),
                        ),
                      ),
                      Positioned(
                        left: 1155,
                        top: 14,
                        child: SizedBox(
                          width: 85,
                          child: Text(
                            'FAMILY SITE',
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w400,
                              height: 1,
                              letterSpacing: -0.24,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 268,
                        top: 14,
                        child: SizedBox(
                          width: 44,
                          child: Text(
                            '회사소개',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w400,
                              height: 1,
                              letterSpacing: -0.24,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 176,
                        top: 14,
                        child: SizedBox(
                          width: 44,
                          child: Text(
                            '법적고지',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w400,
                              height: 1,
                              letterSpacing: -0.24,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 40,
                        top: 14,
                        child: SizedBox(
                          width: 88,
                          child: Text(
                            '개인정보처리방침',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 12,
                              fontFamily: 'Noto Sans KR',
                              fontWeight: FontWeight.w400,
                              height: 1,
                              letterSpacing: -0.24,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 244,
                        top: 13,
                        child: Container(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          width: 14,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 152,
                        top: 13,
                        child: Container(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                          width: 14,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 142,
                top: 190,
                child: SizedBox(
                  width: 590,
                  height: 36,
                  child: Text(
                    '단 한 번의 조회로 정확한 시세 분석',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 36,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w700,
                      height: 0.89,
                      letterSpacing: -0.72,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 142,
                top: 251,
                child: SizedBox(
                  width: 691,
                  height: 86,
                  child: Text(
                    '방대한 데이터를 학습한 AI가 데이터를 종합 분석하여, \n자전거의 현재 시세부터 미래 가치까지 정밀하게 제공합니다. \n복잡한 데이터 해석 없이도, 누구나 손쉽게 신뢰할 수 있는 가격 정보를 확인할 수 있습니다. ',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 18,
                      fontFamily: 'Noto Sans KR',
                      fontWeight: FontWeight.w500,
                      height: 1.56,
                      letterSpacing: -0.36,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}